# 1. 판다스(Pandas)

In [1]:
import pandas as pd # 라이브러리 불러오기
pd.__version__ # 버전 확인

'0.24.2'

## 1) 시리즈(Series)
> 표에서 열(column)에 해당하는 데이터 구조이며 각 값에 인덱스(index)가 부여된다. 

In [2]:
sr=pd.Series([17000, 18000, 1000, 5000],
            index=["피자", "치킨", "콜라", "맥주"])
print(sr)

피자    17000
치킨    18000
콜라     1000
맥주     5000
dtype: int64


In [3]:
print(sr.values)

[17000 18000  1000  5000]


In [4]:
print(sr.index)

Index(['피자', '치킨', '콜라', '맥주'], dtype='object')


## 2) 데이터프레임(DataFrame)
> 가장 많이 쓰이는 데이터 구조로, 일반적인 표와 같이 행(raw), 열(column)로 구성되며 행과 열은 각각 index를 가진다. 

In [6]:
values=[[1,2,3], [4,5,6], [7,8,9]]
index=['one', 'two', 'three']
columns=['A', 'B', 'C']

df=pd.DataFrame(values, index=index, columns=columns)
df

A  B  C
one    1  2  3
two    4  5  6
three  7  8  9

In [7]:
print(df.index) # 인덱스 출력

Index(['one', 'two', 'three'], dtype='object')


In [8]:
print(df.columns) # 열 출력

Index(['A', 'B', 'C'], dtype='object')


In [9]:
print(df.values) # 값 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 3) 데이터 프레임 생성
> 데이터프레임은 리스트(list), 시리즈, 딕셔너리(dict), Numpy의 ndarrays와 또다른 데이터프레임으로 생성할 수 있다. 우선 list와 dict를 통해 데이터 프레임을 생성한다.

In [11]:
# 리스트로 데이터프레임 생성
data=[
    ['1000', 'Steve', 90.72],
    ['1001', 'James', 78.09],
    ['1002', 'Doyeon', 98.43],
    ['1003', 'Jane', 64.19],
    ['1004', 'Pilwoong', 81.30],
    ['1005', 'Tony', 99.14]
]
df=pd.DataFrame(data)
df

0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

In [12]:
# 생성된 데이터프레임에 columns 지정
df=pd.DataFrame(data, columns=['학번', '이름', '점수'])
df

학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

In [13]:
# dict로 데이터프레임 생성
data={'학번':['1000', '1001', '1002', '1003', '1004', '1005'],
     '이름':['Steve', 'James', 'Doyeon', 'Jane', 'Pilwoong', 'Tony'],
     '점수':[90.72, 78.09, 98.43, 64.19, 81.30, 99.14]}

df=pd.DataFrame(data)
df

학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

## 4) 데이터프레임 조회하기

In [14]:
df.head() # 앞부분 조회(default=5)

학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30

In [15]:
df.tail() # 뒷부분 조회(default=5)

학번        이름     점수
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

In [16]:
df['학번'] # column 조회

0    1000
1    1001
2    1002
3    1003
4    1004
5    1005
Name: 학번, dtype: object

## 5) 외부 데이터 읽기
> 데이터 분석 시 만들기보다는 이미 존재하는 데이터를 불러오는 일이 많다. 예시로 쓰인 데이터는 kaggle의 [로스앤젤레스 범죄 데이터](https://www.kaggle.com/search?q=crime+dataset+in%3Adatasets)이다.

In [17]:
df=pd.read_csv('data/Crime_Data_2010_2017.csv', index_col=0) # index열을 따로 만들지 않는다

C:\Users\CUCHO\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [19]:
df.head()

Date Reported Date Occurred  Time Occurred  Area ID    Area Name  \
DR Number                                                                    
1208575      03/14/2013    03/11/2013           1800       12  77th Street   
102005556    01/25/2010    01/22/2010           2300       20      Olympic   
418          03/19/2013    03/18/2013           2030       18    Southeast   
101822289    11/11/2010    11/10/2010           1800       18    Southeast   
42104479     01/11/2014    01/04/2014           2300       21      Topanga   

           Reporting District  Crime Code  \
DR Number                                   
1208575                  1241         626   
102005556                2071         510   
418                      1823         510   
101822289                1803         510   
42104479                 2133         745   

                             Crime Code Description             MO Codes  \
DR Number                                                                  
1208575           INTIMATE PARTNER - SIMPLE ASSAULT  0416 0446 1243 2000   
102005556                          VEHICLE - STOLEN                  NaN   
418                                VEHICLE - STOLEN                  NaN   
101822289                          VEHICLE - STOLEN                  NaN   
42104479   VANDALISM - MISDEAMEANOR ($399 OR UNDER)                 0329   

           Victim Age  ...                              Weapon Description  \
DR Number              ...                                                   
1208575          30.0  ...  STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)   
102005556         NaN  ...                                             NaN   
418              12.0  ...                                             NaN   
101822289         NaN  ...                                             NaN   
42104479         84.0  ...                                             NaN   

          Status Code  Status Description Crime Code 1  Crime Code 2  \
DR Number                                                              
1208575            AO         Adult Other        626.0           NaN   
102005556          IC         Invest Cont        510.0           NaN   
418                IC         Invest Cont        510.0           NaN   
101822289          IC         Invest Cont        510.0           NaN   
42104479           IC         Invest Cont        745.0           NaN   

          Crime Code 3 Crime Code 4                                  Address  \
DR Number                                                                      
1208575            NaN          NaN  6300    BRYNHURST                    AV   
102005556          NaN          NaN                                 VAN NESS   
418                NaN          NaN   200 E  104TH                        ST   
101822289          NaN          NaN                                     88TH   
42104479           NaN          NaN  7200    CIRRUS                       WY   

           Cross Street             Location   
DR Number                                      
1208575             NaN  (33.9829, -118.3338)  
102005556          15TH  (34.0454, -118.3157)  
418                 NaN   (33.942, -118.2717)  
101822289          WALL  (33.9572, -118.2717)  
42104479            NaN  (34.2009, -118.6369)  

[5 rows x 25 columns]

In [21]:
print(df.index) # index_col 옵션을 지정하였으므로 index는 DR Number 열과 같다

Int64Index([  1208575, 102005556,       418, 101822289,  42104479, 120125367,
            101105609, 101620051, 101910498, 120908292,
            ...
            172116472, 172116473, 172116474, 172116478, 172116479, 172116482,
            172116489, 172116491, 172116498, 172116510],
           dtype='int64', name='DR Number', length=1584316)


# 2. 넘파이(Numpy)
- 주요 모듈
    1. np.array() # list, 튜플(tuple), 배열로부터 ndarray를 생성
    2. np.asarray() # 기존의 array로부터 ndarray를 생성
    3. np.arange() # range와 비슷한 역할, 범위를 지정
    4. np.linspace(start, end, num) # [start, end] 균일한 간격으로 num개만큼 생성
    5. np.logspace(start, end, num) # [start, end] log scale 간격으로 num개만큼 생성

In [2]:
import numpy as np # 라이브러리 불러오기
np.__version__ # 버전 체크

'1.16.2'

## 1) np.array()

In [3]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [4]:
b=np.array([[10,20,30], [60,70,80]])
print(b)

[[10 20 30]
 [60 70 80]]


In [5]:
print(b.ndim) # 차원 출력
print(b.shape) # 크기 출력

2
(2, 3)


In [6]:
print(a.ndim)
print(a.shape)

1
(5,)


## 2) ndarray의 초기화
> 다음과 같은 함수를 활용해 ndarray를 만들어낼 수 있다.

- np.zeros(): 해당 배열이 모두 0인 ndarray를 만든다.
- np.ones(): 해당 배열이 모두 1인 ndarray를 만든다.
- np.full(): 해당 배열을 사용자가 지정한 값으로 채운다.
- np.eye(): 해당 배열을 대각선으로는 1, 나머지 부분은 0으로 채운다.

In [9]:
a=np.zeros((2,3)) # 모든 값이 0인 2x3 배열 생성
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
a=np.ones((2,3)) # 모든 값이 1인 2x3배열 생성
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
a=np.full((2,3), 9) # 모든 값이 9인 2x3 배열 생성
print(a)

[[9 9 9]
 [9 9 9]]


In [14]:
a=np.eye(3) # 대각선으로 1이고 나머지는 0인 3x3 배열 생성
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
a=np.random.random((2,3)) # 임의의 값으로 채워진 2x3 배열 생성
print(a)

[[0.58985218 0.03456012 0.26410657]
 [0.48209931 0.87991674 0.55868947]]


## 3) np.arange()
> 사용자가 지정한 범위 내의 값으로 구성된 배열을 생성한다.

- numpy.arange(start, stop, step, dtype)
    - a=np.arange(n) # 0, ...., n-1까지 범위 지정
    - a=np.arange(i,j,k) # i부터 j-1까지 k씩 증가하는 배열 생성

In [17]:
a=np.arange(10) # 0부터 9까지 값 범위 지정
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
a=np.arange(1, 10, 2) # 1부터 9까지, +2 간격의 값들로 배열 생성
print(a)

[1 3 5 7 9]


## 4) reshape()
> 생성한 배열의 차원을 변경하여 새로운 배열을 만든다.

In [21]:
a=np.array(np.arange(30))
a_=np.array(np.arange(30)).reshape((5,6))
print('원래 배열(1차원):', a)
print('변환된 배열(2차원):', a_)

원래 배열(1차원): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
변환된 배열(2차원): [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


## 5) Numpy 슬라이싱

In [24]:
a=np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [23]:
b=a[0:2, 0:2]
print(b)

[[1 2]
 [4 5]]


In [25]:
b=a[0, :] # 첫번째 행 출력
print(b)

[1 2 3]


In [26]:
b=a[1, :] # 두번째 행 출력
print(b)

[4 5 6]


In [28]:
b=a[:, 0] # 첫번째 열 출력
print(b)

[1 4]


In [30]:
b=a[:, 1] # 두번째 열 출력
print(b)

[2 5]


In [31]:
b=a[:, 2] # 세번째 열 출력
print(b)

[3 6]


## 6) Numpy 정수 인덱싱(integer indexing)
> 원본 배열로부터 부분 배열 구하기

In [33]:
a=np.array([[1,2], [4,5], [7,8]])
b=a[[2,1], [1,0]]
print(b)

[8 4]


## 7) Numpy 연산
> 배열 간 연산은 +,-,/,* 등의 연산자로 쉽게 할 수 있다. 물론 add(), subtract(), multiply(), divide() 등의 함수를 사용할 수도 있다.

In [34]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [35]:
b=x+y # 각 요소를 더함
# b=np.add(x,y)와 동일함
print(b)

[5 7 9]


In [36]:
b=x-y # 각 요소에 대해서 빼기
# b=np.subtract(x,y)와 동일함
print(b)

[-3 -3 -3]


In [37]:
b=x*y # 각 요소에 대해서 곱셈 
# b=np.multiply(x,y)와 동일함
print(b)

[ 4 10 18]


In [38]:
b=b/x # 각 요소에 대해서 나눗셈
# b=np.divide(b,x)와 동일함
print(b)

[4. 5. 6.]


In [42]:
# 벡터와 행렬곱
a=np.array([[1,2], [3,4]])
b=np.array([[5,6], [7,8]])

c=np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


In [43]:
# a, b의 형태 확인
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


# 3. 맷플롯립(Matplotlib)

In [44]:
import matplotlib as mpl # 라이브러리 불러오기
mpl.__version__ # 버전 확인

'3.0.3'

In [47]:
# 주피터 노트북에 그림을 표시하도록 지정함
%matplotlib inline 
import matplotlib.pyplot as plt

## 1) 라인 플롯 그리기